"""init

Revision ID: c64f705fd6ae
Revises:
Create Date: 2023-04-12 20:32:31.187331

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c64f705fd6ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
