"""init

Revision ID: d8eeac7b1914
Revises: 
Create Date: 2023-04-19 20:46:56.883366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8eeac7b1914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id_channel', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('subs_total', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id_channel')
    )
    op.create_table('post',
    sa.Column('id_post', sa.BigInteger(), nullable=False),
    sa.Column('id_channel', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('id_channel_forward_from', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_channel'], ['channel.id_channel'], ),
    sa.ForeignKeyConstraint(['id_channel_forward_from'], ['channel.id_channel'], ),
    sa.PrimaryKeyConstraint('id_post', 'id_channel')
    )
    op.create_table('sub_per_day',
    sa.Column('id_sub_per_day', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subs', sa.BigInteger(), nullable=False),
    sa.Column('id_channel', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_channel'], ['channel.id_channel'], ),
    sa.PrimaryKeyConstraint('id_sub_per_day')
    )
    op.create_table('mention',
    sa.Column('id_mentioned_channel', sa.BigInteger(), nullable=False),
    sa.Column('id_post', sa.BigInteger(), nullable=False),
    sa.Column('id_channel', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_mentioned_channel'], ['channel.id_channel'], ),
    sa.ForeignKeyConstraint(['id_post', 'id_channel'], ['post.id_post', 'post.id_channel'], ),
    sa.PrimaryKeyConstraint('id_mentioned_channel', 'id_post', 'id_channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mention')
    op.drop_table('sub_per_day')
    op.drop_table('post')
    op.drop_table('channel')
    # ### end Alembic commands ###
